plugins {
    id 'java-library'
	id 'org.springframework.boot' version '3.5.8'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.amuraedo'
version = '0.0.1-SNAPSHOT'
description = 'module-common'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

bootJar{ enabled = false}
jar { enabled = true}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	compileOnly 'org.projectlombok:lombok'

	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

// [수정] 0.12.5로 통일
    api 'io.jsonwebtoken:jjwt-api:0.12.5'

// [수정] 0.11.5 -> 0.12.5 로 변경 필수!
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'

    api 'com.fasterxml.jackson.core:jackson-databind'
}

tasks.named('test') {
	useJUnitPlatform()
}
